apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panvala-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "panvala-frontend.name" . }}
    helm.sh/chart: {{ include "panvala-frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "panvala-frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "panvala-frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: API_HOST
              value: {{ .Values.apiHost }}
            - name: NODE_ENV
              value: {{ .Values.node_env }}
            - name: PANVALA_ENV
              value: {{ .Values.panvala_env }}
            # Contract info
            - name: GATEKEEPER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: contracts-config
                  key: gatekeeper
            - name: TOKEN_CAPACITOR_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: contracts-config
                  key: tokenCapacitor
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
