apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  name: {{ .Values.databaseName }}
  user: {{ .Values.databaseUser }}
  host: {{ .Values.databaseHost }}
  port: {{ .Values.databasePort | quote }}
