# Default values for panvala-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# The host of the database to be exposed to the cluster as a service
databaseExternalHost: localhost

# database config
# The database host that the other services will point to
databaseHost: panvala-db
databasePort: 5432
databaseName: panvala_api
databaseUser: panvala
databasePassword: password


# contract addresses
gatekeeper: "0xcc20cbD0F5534f85F0042eC99Fd1C4f4608a31B9"
tokenCapacitor: "0x6BAD8c9caDFC59f0f5df904765ebA360A91a59b9"


nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
